apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    app: music1983
    role: master
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: music1983
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
